cbs_types:
  # - CBS
  # - MACBS_EPEA
  # - MACBS_EPEA_mr
  # - ECBS
  # - ECBS1
  # - ECBS_rt5
  # - ECBS1_rt5
  # - MAECBS_EPEA
  # - MAECBS_EPEA_mr
  - MAECBS
  # - MAECBS_ro
  # - MAECBS_ro1
  # - MAECBS_ro_rt5
  # - MAECBS_mr
  # - MAECBS_mr1
  # - MAECBS_mrr0
  # - MAECBS_mrr1
focal_w:
- 1.01
# - 1.02
# - 1.05
# - 1.10
# - 1.15
# - 1.20
# map_name: random-32-32-20
# map_name: den520d
map_name: warehouse-20-40-10-2-1
# map_name: maze-32-32-2
merge_th:
- 1
- 25
- 50
- 100
- 150
num_of_agent: 20
plot_common: False
scen_dict:
  even:
  - 0
  random:
  - 0
num_list:
  - 50
  - 100
  - 150
  - 200
  - 250
  # - 300
  # - 10
  # - 20
  # - 30
  # - 40
  # - 50
  # - 60
  # - 70
  # - 80
  # - 90
  # - 100
