# function: 'plot_num_success'
function: 'plot_num_runtime'
cbs_types:
- ECBS
- MACBS
- MAECBS
focal_w:
- 1.10
# - 2.00
map_name: den520d
merge_th:
- 1
- 10
- 50
num_of_agent: 50
scen_dict:
  even:
  - 0
  random:
  - 0