function: 'plot_time_soc'
cbs_types:
- ECBS
- MACBS
- MAECBS
focal_w:
- 1.1
- 1.2
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9
map_name: random-32-32-20
merge_th:
- 1
- 10
num_of_agent: 50
scen_dict:
  even:
  - 0
  random:
  - 0
