# function: 'plot_weight_runtime'
function: 'plot_weight_subopt'
cbs_types:
- ECBS
# - MAECBS
focal_w:
- 1.1
- 1.2
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9
- 2.0
# map_name: random-32-32-20
# map_name: den520d
map_name: ost003d
merge_th:
- 1
- 10
- 50
num_of_agent: 50
scen_dict:
  # even:
  # - 0
  random:
  - 0
